INSERT INTO category(id,name) VALUES (1,'Amusementsspelen');
INSERT INTO category(id,name) VALUES (2,'Borden en bestek');
INSERT INTO category(id,name) VALUES (3,'Decoratie');
INSERT INTO category(id,name) VALUES (4,'Diensten');
INSERT INTO category(id,name) VALUES (5,'DJ Service');
INSERT INTO category(id,name) VALUES (6,'Leveren van drank');
INSERT INTO category(id,name) VALUES (7,'Geluid & Licht');
INSERT INTO category(id,name) VALUES (8,'Glaswerk');
INSERT INTO category(id,name) VALUES (9,'Keukengerei - Buffet');
INSERT INTO category(id,name) VALUES (10,'Koeling');
INSERT INTO category(id,name) VALUES (11,'Podiumelementen');
INSERT INTO category(id,name) VALUES (12,'Springkussen');
INSERT INTO category(id,name) VALUES (13,'Sky puppets - Skydancers');
INSERT INTO category(id,name) VALUES (14,'Stoelen');
INSERT INTO category(id,name) VALUES (15,'Schilderwerken');
INSERT INTO category(id,name) VALUES (16,'Tafels');
INSERT INTO category(id,name) VALUES (17,'Tenten');
INSERT INTO category(id,name) VALUES (18,'Tafellinnen');
INSERT INTO category(id,name) VALUES (19,'Trampoline Magic Circle');
INSERT INTO category(id,name) VALUES (20,'Tap en toog');
INSERT INTO category(id,name) VALUES (21,'Verlichting');
INSERT INTO category(id,name) VALUES (22,'Vestaire');
INSERT INTO category(id,name) VALUES (23,'Verwarming');
INSERT INTO category(id,name) VALUES (24,'Toilet');
